name: Go

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: sudo apt install libappindicator3-dev gir1.2-appindicator3-0.1 gcc libc6-dev libx11-dev xorg-dev libxtst-dev  libpng++-dev  xcb libxcb-xkb-dev x11-xkb-utils libx11-xcb-dev libxkbcommon-x11-dev libxkbcommon-dev && go build -v ./...

    - name: Test
      run: go test -v ./...
